# Generated by Django 4.1.4 on 2022-12-11 17:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import apps.cars.services


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auto_parks', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=12, unique=True)),
                ('year', models.IntegerField(default=2000, validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2022)])),
                ('seats_count', models.IntegerField(default=4)),
                ('body', models.CharField(max_length=12)),
                ('engine_volume', models.FloatField(default=2.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auto_park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='auto_parks.autoparkmodel')),
            ],
            options={
                'db_table': 'cars',
            },
        ),
        migrations.CreateModel(
            name='CarPhotosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to=apps.cars.services.upload_car_photo)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='cars.carmodel')),
            ],
            options={
                'db_table': 'cars_photos',
            },
        ),
    ]
