# Generated by Django 4.1.4 on 2022-12-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='price',
            field=models.IntegerField(default=5000),
        ),
    ]
