# Generated by Django 4.1.4 on 2022-12-10 15:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profilemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='', verbose_name='avatars'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='name',
            field=models.CharField(max_length=18, validators=[django.core.validators.RegexValidator(('^[a-zA-Z]{2,15}$',), 'only letters, length from 2 to 20 chars')]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(('^\\+380[9683]{2}[0-9]{7}$',), 'invalid phone number')]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='surname',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(('^[a-zA-Z]{2,15}$',), 'only letters, length from 2 to 20 chars')]),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(('^(?=.*[a-z])(?=.*[A-Z])(?=.*[^\\w\\s])(?=.*[\\d])[^\\s]{5,20}$',), ['password must have at least 1 lowercase letter', 'password must have at least 1 uppercase letter', 'password must have at least 1 number', 'password must have at least 1 special symbol'])]),
        ),
    ]
